name: Docker Image CI

on:
  push:
    branches:
      - main  # Veya hangi branch'ten push yapılmasını istiyorsanız onu yazın.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name:${{ github.sha }} .
          
      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/your-image-name:${{ github.sha }}
